name: Jobs-Test
on:
  push:
    branches:
      - master
  workflow_call:
    inputs:
      username:
        description: 'A username in git'
        default: 'AnnalisKirwa'
        required: false
        type: string
    outputs:
      workflow_output1:
        description: "The first output"
        value: 'rtyuio'
jobs:
  print-username:
    runs-on: ubuntu-latest
    name: Job_One
    steps:
    - name: Display my github username
      run: |
        echo "My github username is ${{ inputs.username }}"
  print-username-one:
    runs-on: ubuntu-latest
    name: Job_Two
    steps:
    - name: Display my github username
      run: |
        echo "My github username is ${{ outputs.workflow_output1 }}"
