#updates values
name: pipeline
on: [push]
jobs:
  update_values:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the test repository
        run: |
          git clone https://github.com/Annaliskirwa/_Test.git
          echo "Cloned the repository"
      - name: Switching folder
        run: |
          ls -la
          echo "Switching folders"
          cd _Test
          sleep 5
      - name: Switching branches
        run: |
          git branch -la
          git switch master
          echo "Switched branch to master"
      - name: Update image tag for values.yaml file
        run: |
          if [-f values.yaml];
            then sed -ri '1,/^(\s*)(tag*)/ s/^(\s*)(tag*:[[:blank:]]*).*/\1tag: "today"/'  values.yaml;
          fi
          echo "updated the image tag to today"

