#updates values
name: pipeline
on: [push]
jobs:
  update_values:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the test repository
        run: |
          git clone https://github.com/Annaliskirwa/_Test.git
          echo "Cloned the repository"
      - name: Updating the image tags for master
        run: |
          ls -la
          echo "Switching folders"
          cd _Test
          git switch master
          echo "Switched branch to master"
      - name: Update image tag for values.yaml file
        run: |
          echo "Trying to update image tags"
          if [ -f values.yaml ];
            then sed -ri '1,/^(\s*)(tag*)/ s/^(\s*)(tag*:[[:blank:]]*).*/\1tag: "today"/'  values.yaml;
          fi
          echo "updated the image tag to today"
          cat values.yaml

