name: Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Continuous Integration For Changing Tag in Test Repo
      CI_COMMIT_AUTHOR: Annaliskirwa
      CI_COMMIT_EMAIL: annaliskirwa@gmail.comx
      IMAGE_TAG: ${{ $((RANDOM)) }}
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
        repository: Annaliskirwa/_Test
        ref: 'master'
    - name: Clone the test repository
      run: |
        git clone https://github.com/Annaliskirwa/_Test.git
        # git clone https://Annaliskirwa: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@github.com/Annaliskirwa/_Test.git
        echo "Cloned the repository"
    - name: Switching to master
      run: |
        ls -la
        echo "Switching folders"
        cd _Test
        ls -la
        git switch master
        echo "Switched branch to master"
    - name: Update image tag for values profiles file
      run: |
        cd _Test
        echo "Trying to update image tags"
        # export IMAGE_TAG=$((RANDOM))
        # setEnvVar "IMAGE_TAG" "$((RANDOM))"
        echo "The image tag is: ${{ env.IMAGE_TAG }}"
        pwd
        echo "Updating values yaml"
        if [ -f values.yaml ];
          then sed -ri "1,/^(\s*)(tag*)/ s/^(\s*)(tag*:[[:blank:]]*).*/\1tag: "$IMAGE_TAG"/"  values.yaml;
        fi

        echo "Updating values-test yaml"
        if [ -f values-test.yaml ];
          then sed -ri "1,/^(\s*)(tag*)/ s/^(\s*)(tag*:[[:blank:]]*).*/\1tag: "$IMAGE_TAG"/"  values-test.yaml;
        fi

        echo "Updating values-prod yaml"
        if [ -f values-prod.yaml ];
          then sed -ri "1,/^(\s*)(tag*)/ s/^(\s*)(tag*:[[:blank:]]*).*/\1tag: "$IMAGE_TAG"/"  values-prod.yaml;
        fi

        echo "updated the image tag to ${{ env.IMAGE_TAG }}"
        # echo "updated the image tags to $IMAGE_TAG"
        cat values.yaml

    - name: Commit the changes
      run: |
        cd _Test
        pwd
        ls -la
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"
        git add .
        git commit -am "${{ env.CI_COMMIT_MESSAGE }}"
        echo "Committed successfully"
    - name: Push the changes
      run: |
        cd _Test
        git push https://${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}@github.com/Annaliskirwa/_Test.git HEAD:master --force
        echo "Pushed successfully"
    - name: Switching to ft_values
      run: |
        cd _Test
        git switch ft_values
        echo "Switched branch to ft_values"
    - name: Updating image tag for values pre prod yaml
      run: |
        cd _Test
        # echo "The env for tag is: $IMAGE_TAG"
        echo "The image tag is: ${{ env.IMAGE_TAG }}"
        if [ -f values-pre-prod.yaml ];
          then sed -ri "1,/^(\s*)(tag*)/ s/^(\s*)(tag*:[[:blank:]]*).*/\1tag: "$IMAGE_TAG"/"  values-pre-prod.yaml;
        fi
        cat values-pre-prod.yaml
    - name: Commiting changes for values pre prod yaml
      run: |
        cd _Test
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"
        git add .
        git commit -am "${{ env.CI_COMMIT_MESSAGE }}"
        echo "Committed successfully"
    - name: Push the changes to ft_values
      run: |
        cd _Test
        git push https://${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}@github.com/Annaliskirwa/_Test.git HEAD:ft_values --force
        echo "Pushed successfully"




    

